name: myflutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  # 添加sharedPreference依赖
  shared_preferences: ^0.5.0
  flutter_webview_plugin: ^0.3.8
  flutter_cupertino_date_picker: ^1.0.12
  date_format: ^1.0.8
  #添加刷新控件
  pull_to_refresh: ^1.5.7
  #轮播控件
  flutter_swiper: ^1.1.6
  #滚轮组件
  wheel_chooser: ^0.0.1
  #图片选择器组件
  image_picker: ^0.6.1+10
  #图片压缩工具
  #获取相册路径
  path_provider: ^1.4.0
  #flutter_luban: ^0.1.7+1
  #二维码
  qr_flutter: ^3.0.1
  #Radio 插件
  cached_network_image: ^1.1.3
  #保存图片到相册插件
  image_picker_saver: ^0.3.0
  #amap_base: ^0.3.5
  permission_handler: ^4.0.0
  flutter_qr_reader: ^1.0.3
  flutter_native_image: ^0.0.4
  contact_picker: ^0.0.2
  package_info: ^0.4.0+2
  sensors: ^0.4.0+1
  audioplayers: ^0.13.1
  wave_progress_bars: ^0.1.0
  mobsms: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
aasets:
  - images/main_title.png
  - images/ic_time_out.png
  - images/ic_my_head.png
  - images/ic_head_blue.png
  - images/ic_foot_step.png
  - images/ic_phone.png
  - images/ic_password.png
  - images/ic_show_pwd_gray.png
  - images/ic_hide_pwd_gray.png
  - images/ic_identify.png
  - images/ic_wechat.png
  - images/ic_no_data.png
  - images/ic_del.png
  - images/ic_arrow_navigathion.png
  - images/ic_order_photo.png
  - images/no_banner.png
  - images/change_content.png
  - images/ic_currect.png
  - images/ic_button_erweima.png
  - images/ic_blue_merge.png
  - images/ic_gray_merge.png
  - images/ic_closed.png
  - images/ic_gaode.png
  - images/ic_baidu.png
  - images/ic_tengxun.png
  - images/ic_goole.png
  - images/ic_blue_navigation.png
  - images/ic_amplify.png
  - images/ic_question.png
  - images/jidier_erweima.png
  - images/ic_qq.png
  - images/ic_wei_chat.png
  - images/ic_zhifubao.png
  - images/mark_adress.png
  - images/locaiton1.png
  - images/map_bottom.png
  - images/ic_red_location.png
  - images/ico_end_marker.png
  - images/ic_scan_erweima.png
  - images/ic_ji.png
  - images/ic_shorter.png
  - images/ios_ico.png
  - images/ico_packing.png
  - images/ico_no_data.png
  - images/address_record1.png
  - images/ico_way_planting.png
  - images/ico_eye.png
  - images/ico_history_plan.png
  - images/ico_location.png
  - images/ico_start.png
  - images/ico_end.png
  - images/ico_green_location.png
  - images/ico_red_location.png
  - images/ico_contacts.png
  - images/ic_contact_pic.png
  - images/ic_speak_gray.png
  - images/ic_speak_red.png
  - images/ico_setting.png
  - images/ic_blue_message.png
  - images/ic_system_notice.png
  - images/ico_version.png
  - images/ic_shake_gry.png
  - images/ic_shake_red.png
  - images/ic_speaker.png
  - assets/start.mp3
  - assets/faild.mp3
  - assets/firstlogin.mp3
  - assets/nolocation.mp3
  - assets/successful.mp3

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
